name: artefakt

on:
  workflow_dispatch:

jobs:
  tworzenie:
    runs-on: ubuntu-latest
    steps:
      - name: Utwórz raport
        run: |
          mkdir -p raport
          uname -a > raport/raport.txt
          date >> raport/raport.txt
          cat raport/raport.txt

      - name: Wyślij raport jako artefakt
        uses: actions/upload-artifact@v7
        with:
          name: raport
          path: raport/raport.txt

  odczyt:
    runs-on: ubuntu-latest
    needs: tworzenie
    steps:
      - name: Zawartość katalogu przed pobraniem
        run: ls -la

      - name: Pobierz artefakt
        uses: actions/download-artifact@v8
        with:
          name: raport

      - name: Odczytaj raport
        run: |
          ls -la
          cat raport.txt
