name: Przykladowy warunkowy przeplyw

on:
  workflow_dispatch:

jobs:
  testy_warunku:
    runs-on: ubuntu-latest
    outputs:
      jadro: ${{ steps.jadro_kroku.outputs.KERNEL }}
    steps:
      - name: Wyświetl podstawowe informacje
        run: |
          echo "Uruchomiono przepływ GitHub Actions"
          echo "Aktualna data: $(date)"

      - name: Pobierz wersję jądra
        id: jadro_kroku
        run: |
          KERNEL=$(uname -r)
          echo "KERNEL=$KERNEL" >> $GITHUB_OUTPUT

      - name: Wyświetl informację, jeśli jądro jest 6.x
        if: startsWith(steps.jadro_kroku.outputs.KERNEL, '6.')
        run: echo "Wykryto jądro 6.x - warunek został spełniony, i zadanie zostało wykonane!"

      - name: Inny komunikat dla innego jądra
        if: ${{ !startsWith(steps.jadro_kroku.outputs.KERNEL, '6.') }}
        run: echo "Wykryto jądro inne niż 6.x — to zadanie zostało wykonane zamiast poprzedniego."

      - name: Uruchom zawsze
        if: always()
        run: echo "Zawsze"

      - name: Uruchom po awarii
        if: failure()
        run: echo "Po awarii"

      - name: Uruchom po sukcesie
        if: success()
        run: echo "Po sukcesie"

  drugie_zadanie:
    runs-on: ubuntu-latest
    needs: testy_warunku
    if: failure()
    steps:
      - name: Drugie zadanie
        run: echo "Drugie zadanie wykonane"

      - name: Wyświetl jądro z zadania testy_warunku
        run: echo "Jądro w zadaniu testy_warunku to $JADRO_TESTY"
        env:
          JADRO_TESTY: ${{ needs.testy_warunku.outputs.jadro }}
