name: Maskowanie wartości

on:
  workflow_dispatch:

jobs:
  maskowanie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Odszyfrowanie i maskowanie klucza API
        env:
          HASLO_GPG: ${{ secrets.HASLO_GPG1 }}
        run: |
          mkdir -p $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$HASLO_GPG" --output $HOME/secrets/sekret.json sekret.json.gpg
          KLUCZ_API=$(jq -r '.api_key' $HOME/secrets/sekret.json)
          echo "::add-mask::$KLUCZ_API"
          echo "Klucz API odczytany z pliku to $KLUCZ_API"
          echo "KLUCZ_API=$KLUCZ_API" >> $GITHUB_ENV

      - name: Klucz API w kolejnym kroku
        run: echo "W kolejnym kroku klucz API to $KLUCZ_API"

      - name: Usunięcie pliku odszyfrowanego
        if: always()
        run: rm -rf $HOME/secrets
